/* ============================================================
   FED PLAY · ULTIMATE APP STORE — SHARED DATA LAYER
   Central catalog of apps. Each app can belong to multiple tabs.
   ============================================================ */
const APPS = [
    // ===== CREATIVE =====
    {
        id: "deviantart",
        name: "DeviantArt",
        category: "creative",
        featured: true,
        rating: 4.8, reviews: "2.1k",
        description: "Massive art community for sharing digital art, fan art, and original characters.",
        downloadUrl: "https://download1583.mediafire.com/ruryrzsmpopgo_F6U1fiw824xPidfHf8z5PUylMMN3DQP_Q3ID3eKvuQv4lG2mItQ9dQ66tZPJTikY7r0JXdjxiXAWy54xU1I5cg_gSXWI0QkyRT9Et91QIDLcPXi3R-z4WTUrfvdb_tJp7fc5AdV6TlO5MWUs8Y-GQYK8O4H019ToM/x7fxbpe7ak6bxq4/dev+art+%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "fed_originals", "missing"],
        imageUrl: "https://images.icon-icons.com/2972/PNG/512/deviantart_logo_icon_186874.png"
    },
    {
        id: "midjourney",
        name: "Midjourney",
        category: "creative",
        featured: false,
        rating: 4.9, reviews: "3.2k",
        description: "AI image generation from text prompts — concept art & experimental visuals.",
        downloadUrl: "https://download946.mediafire.com/ie2zdxq0xtcg4frQQl3NAgGvphxIj1SQmsCelTpbDEcROe8WNtlAcOGVgE8iw02OzT7lZfE3yhg-vrQAskA86IVWtT6Kl2AUvwq9kR5EEq5VF938xnmFMv4GtMROF5vijZURlhu19gqPAOzhhX5CT4r5wTMZ23eJCs_dyjfNhASI_wM/ikrld20p2ycl64e/Mid+journey+%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "missing"],
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png"
    },
    {
        id: "artstation",
        name: "ArtStation",
        category: "creative",
        featured: false,
        rating: 4.7, reviews: "1.4k",
        description: "Showcase platform for professional artists in games, film, and media.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "missing"],
        imageUrl: "https://cdn.simpleicons.org/artstation/13A3D6"
    },
    {
        id: "behance",
        name: "Behance",
        category: "creative",
        featured: false,
        rating: 4.6, reviews: "980",
        description: "Adobe's portfolio network for creatives to showcase and discover work.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "missing"],
        imageUrl: "https://cdn.simpleicons.org/behance/1769FF"
    },
    {
        id: "pixiv",
        name: "Pixiv",
        category: "creative",
        featured: true,
        rating: 4.8, reviews: "5.1k",
        description: "Japan's largest illustration community — manga, anime, and fan art.",
        downloadUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "missing"],
        imageUrl: "https://cdn.simpleicons.org/pixiv/0096FA"
    },

    // ===== SOCIAL =====
    {
        id: "tumbex",
        name: "Tumbex",
        category: "social",
        featured: false,
        rating: 4.5, reviews: "890",
        description: "Third-party Tumblr viewer with cleaner layout for blogs and photo archives.",
        downloadUrl: "https://download1326.mediafire.com/5fum0s8zk9dggWInT1-UZ9EuaY-t58MPp8v2RgxM2nRMOffcZkHemJlf6W7G53YHi1JdL-fm7HiQVbI9wzgOWKqKK_T07AI4ywKO7zk5Uk-Jby7VFCyHlrdWAUkl93GgrD9Jr-OYdeR46021IzG19fTJbVM5eCUE4uwQlgZ1wWi5jyw/160y2mswn3jisam/Tumbex%281%29.apk",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "social", "missing"],
        imageUrl: "https://cdn.mos.cms.futurecdn.net/ge36mrFPXqtx8p57b2sT5U.jpg"
    },
    {
        id: "kofi",
        name: "Ko-fi",
        category: "social",
        featured: true,
        rating: 4.7, reviews: "2.2k",
        description: "Creator-support platform for donations, subscriptions, and digital goods.",
        downloadUrl: "https://download851.mediafire.com/owzbwoluy5dgYhaJN3vckpZQ5KVyK51dI6vi9iipEU5fIsoYq303fDDmHGMHAKhMfzExwhPUGJILgwWVUKIzac7D62PDeOuC-xMtTI5NTEg-ixJAYZsLhbnNMYOOPjcua5F3pVk7vXKOkQwmccPtDErYwx63Y5px_u2dxaH8P3yQ4ek/jvi9cnmq7k1pltu/Ko-Fi+%281%29.apk",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "social", "missing"],
        imageUrl: "https://cdn.prod.website-files.com/5c14e387dab576fe667689cf/670f5a01229bf8a18f97a3c1_favion.png"
    },
    {
        id: "caliee_rae",
        name: "🌸 Caliee Rae Club",
        category: "social",
        featured: false,
        rating: 4.9, reviews: "1.2k",
        description: "Exclusive community for Caliee Rae fans — behind-the-scenes, early access, and more.",
        downloadUrl: "https://www.mediafire.com/file/x6fvgpnpg3gujah/calieeraeapp-release.apk/file",
        editorsChoice: false,
        isPremium: true, isPrivate: false, isAppStore: false,
        tags: ["apps", "social", "premium"],
        imageUrl: "https://placehold.co/400x400/fbbf24/0c0a1d?text=🌸"
    },
    {
        id: "nexus_chat",
        name: "🔒 Nexus Chat",
        category: "social",
        featured: false,
        rating: 4.6, reviews: "340",
        description: "Private messaging platform for small groups. Request access from the creator.",
        downloadUrl: null,
        editorsChoice: false,
        isPremium: false, isPrivate: true, isAppStore: false,
        creatorContact: "https://t.me/nexuscreator",
        tags: ["apps", "social", "private"],
        imageUrl: "https://placehold.co/400x400/60a5fa/0c0a1d?text=💬"
    },
    {
        id: "mastodon",
        name: "Mastodon",
        category: "social",
        featured: false,
        rating: 4.4, reviews: "2.7k",
        description: "Decentralized, open-source social network across independent servers.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "social", "missing"],
        imageUrl: "https://cdn.simpleicons.org/mastodon/6364FF"
    },
    {
        id: "bluesky",
        name: "Bluesky",
        category: "social",
        featured: true,
        rating: 4.5, reviews: "3.1k",
        description: "Decentralized microblogging social network built on the AT Protocol.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "social", "missing"],
        imageUrl: "https://cdn.simpleicons.org/bluesky/0085FF"
    },
    {
        id: "discord",
        name: "Discord",
        category: "social",
        featured: false,
        rating: 4.7, reviews: "8.9k",
        description: "Voice, video and text chat for communities and friends across the globe.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "social"],
        imageUrl: "https://cdn.simpleicons.org/discord/5865F2"
    },

    // ===== GAMES =====
    {
        id: "itchio",
        name: "Itch.io",
        category: "games",
        featured: true,
        rating: 4.8, reviews: "1.8k",
        description: "Indie game marketplace — experimental games, game jams, and creative prototypes.",
        downloadUrl: "https://download941.mediafire.com/inz40qhjxkwgdXrRBgsJZyv9f7jKbWwhPyVKBXsJAPwVXJeBbe_FDzmvrm2cWPSqGUGhkZyaw7U2laThVizz0OBAi5PnXZpoZYpIp4SzlBXGDLOonWBt0eNdFb3gVUEWPqSXE-O46JasDp9ycMLgV_zgnM97IwgzUMNgx9_zxMpER2o/p0pza3dvbvn7t4i/itch.io+%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games", "missing"],
        imageUrl: "https://www.destructoid.com/wp-content/uploads/2024/12/Image_Itch.jpg?fit=1200%2C675"
    },
    {
        id: "pokemon_firered",
        name: "Pokémon FireRed",
        category: "games",
        featured: false,
        rating: 4.9, reviews: "5.2k",
        description: "2004 GBA remake of Pokémon Red — updated graphics and post-game content.",
        downloadUrl: "https://download1583.mediafire.com/s2ad1s8s5z2gBTZVBVf41NYLB-8JBOQBw-ZD7s9XeNA2JNIpq9gobrQvN358wYiBfjgSSiSgUv39fijnBpuh6bMb2eeM8iL3YXzp87otTGQtR-S5PQ2Sa1TMifjvHY2bYG5CYP8TQJVo8_h1fIr39-oEZf3RzEika6Mv_OfhN97YIiQ/kv0z0q3e4n6kut1/play+pokemon+fire+red%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games", "missing"],
        imageUrl: "https://www.cubed3.com/wp-content/uploads/2026/02/pokemon-firered-version-nintendo-switch-screenshot-art-1.jpg"
    },
    {
        id: "pokejumper",
        name: "pokejumper",
        category: "games",
        featured: false,
        rating: 4.7, reviews: "2.3k",
        description: "Read Pokémon manga and comics — complete collections, high-res scans, and daily updates.",
        downloadUrl: "https://www.mediafire.com/file/0k03j34pgkcm57x/Pokejumpermangaapp-release.apk/file",
        editorsChoice: false,
        isPremium: true, isPrivate: false, isAppStore: false,
        tags: ["apps", "games", "premium"],
        imageUrl: "https://placehold.co/400x400/ef4444/0c0a1d?text=⚡"
    },
    {
        id: "stardew_valley",
        name: "Stardew Valley",
        category: "games",
        featured: true,
        rating: 4.9, reviews: "12k",
        description: "Inherit your grandfather's old farm and turn it into a thriving homestead.",
        downloadUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games", "missing"],
        imageUrl: "https://placehold.co/400x400/f4a261/0c0a1d?text=🌾"
    },
    {
        id: "minecraft",
        name: "Minecraft",
        category: "games",
        featured: false,
        rating: 4.8, reviews: "45k",
        description: "Build, explore, and survive in endless blocky procedurally-generated worlds.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games"],
        imageUrl: "https://placehold.co/400x400/5b8a3a/0c0a1d?text=⛏️"
    },
    {
        id: "roblox",
        name: "Roblox",
        category: "games",
        featured: false,
        rating: 4.6, reviews: "78k",
        description: "Massive online platform with millions of user-made games and experiences.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games"],
        imageUrl: "https://cdn.simpleicons.org/roblox/000000"
    },
    {
        id: "terraria",
        name: "Terraria",
        category: "games",
        featured: false,
        rating: 4.8, reviews: "9.3k",
        description: "2D sandbox adventure — dig, fight, explore, and build in a vast pixel world.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "games"],
        imageUrl: "https://placehold.co/400x400/FF6B6B/0c0a1d?text=🌲"
    },

    // ===== MOVIES & TV =====
    {
        id: "wco_tv",
        name: "WCO TV",
        category: "movies",
        featured: false,
        rating: 4.6, reviews: "3.4k",
        description: "Streaming site for cartoons, anime, and animated series from multiple eras.",
        downloadUrl: "https://download1338.mediafire.com/cdeshvx1rzpgC9JyTms0sj8EMpDNDiT9NQvPy162HroQd8wLxHmEWu-yQkM8Y_A3f7VRpzzlV2a-7UDWW76ZJBK7okzUUZUh9FR4HHM6K3DMQ2t7JuznyEVTyRPtXN2SwMRkKea9fMR9SniTXnIfY4JuI0_cVh0s0QQs9XnqUA6BeiA/uoq91vgj5j0928p/WCO+TV%281%29.apk",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies", "missing"],
        imageUrl: "https://logos-world.net/wp-content/uploads/2022/06/Thewatchcartoononline-Emblem.png"
    },
    {
        id: "seeflix",
        name: "Seeflix",
        category: "movies",
        featured: true,
        rating: 4.7, reviews: "2.8k",
        description: "Free streaming website — movies and TV shows, no registration required.",
        downloadUrl: "https://download1321.mediafire.com/ydql2bxkf95gNKy4crrgljRWhwO8R5qdPYz0zvUc0pGFkTlk8pmojL4OFfQNDtqhSzGFHSoFgd7rhsskbSAHPfs3ukYBx7JeAJ_DymcO2ZDdnTBDCG6YVL3t4Fn6B5YQ_VPthVqyZ3vIS_YAbaNe_kl71QZEkNLzK909hCyajfeXjGQ/o82jtvlvh43p1be/Seeflix%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies", "missing"],
        imageUrl: "https://logos-world.net/wp-content/uploads/2023/03/SFlix-Logo-2020.png"
    },
    {
        id: "menina_dancando",
        name: "Menina dancando funk",
        category: "movies",
        featured: false,
        rating: 4.8, reviews: "956",
        description: "Brazilian funk dance videos — curated playlists, choreography tutorials, and live streams.",
        downloadUrl: "https://www.mediafire.com/file/ccy71lujks9g7m0/meninaapp-release.apk/file",
        editorsChoice: true,
        isPremium: true, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies", "premium"],
        imageUrl: "https://placehold.co/400x400/22c55e/0c0a1d?text=🕺"
    },
    {
        id: "elite_streams",
        name: "🔒 Elite Streams",
        category: "movies",
        featured: false,
        rating: 4.9, reviews: "210",
        description: "Invite-only streaming platform for indie films and live events. DM the creator.",
        downloadUrl: null,
        editorsChoice: false,
        isPremium: false, isPrivate: true, isAppStore: false,
        creatorContact: "https://twitter.com/elitestreams",
        tags: ["apps", "movies", "private"],
        imageUrl: "https://placehold.co/400x400/60a5fa/0c0a1d?text=🎬"
    },
    {
        id: "crunchyroll",
        name: "Crunchyroll",
        category: "movies",
        featured: true,
        rating: 4.6, reviews: "22k",
        description: "Stream the largest anime library — simulcasts, classics, and Crunchyroll Originals.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies"],
        imageUrl: "https://cdn.simpleicons.org/crunchyroll/F47521"
    },
    {
        id: "tubi",
        name: "Tubi",
        category: "movies",
        featured: false,
        rating: 4.5, reviews: "14k",
        description: "Free, ad-supported streaming with thousands of movies and TV shows.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies"],
        imageUrl: "https://cdn.simpleicons.org/tubi/000000"
    },
    {
        id: "plex",
        name: "Plex",
        category: "movies",
        featured: false,
        rating: 4.4, reviews: "8.1k",
        description: "Personal media server plus free live TV and on-demand movies.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "movies"],
        imageUrl: "https://cdn.simpleicons.org/plex/E5A00D"
    },

    // ===== UTILITY =====
    {
        id: "polymarket",
        name: "Polymarket",
        category: "utility",
        featured: false,
        rating: 4.4, reviews: "612",
        description: "Decentralized prediction market — trade shares on real-world events.",
        downloadUrl: "https://download1584.mediafire.com/49hvgviuscmgTBmq21EIbbMuCp4PPrYbKw3FmeBQUJTqOoLJPC2cbTvG3QvEH4szVUyA7ThGLlwdKGIycwYCs_KjAJIMvT4_8Vuo4fvHlFwGA_FrkcqyoqwWhboSSx9BJY_O8UNZtobSRxfK08x2JfZ8KD93WpTYlu6GQ3E9jl-AAiA/uwcskg1hm2bcsce/polymarket+%281%29.apk",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "missing"],
        imageUrl: "https://polymarket.com/images/brand/icon-blue.png"
    },
    {
        id: "supabase",
        name: "Supabase",
        category: "utility",
        featured: false,
        rating: 4.9, reviews: "1.1k",
        description: "Open-source Firebase alternative — auth, database, storage, and APIs.",
        downloadUrl: "https://download937.mediafire.com/m6ram4t78ghg1To2gx-u1X0x7125otKAXshI-7MHv5nOWyxSEeTTi4sgh-k_lfGqO4Dpa_MhiHV8UTcuKUXdffbdSD9lA_G62D-wVRn1N07TT7J98f8jhHBhDDfglHH5A5l9SHT06ho2fCfgSpt0BayND1h89bgr1j9cyUf3v7wd-RE/nh2xm2e3wlkkw02/supabase+%281%29.apk",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "fed_originals", "missing"],
        imageUrl: "https://miro.medium.com/v2/0*QzPzYLTNRX7p5Rsl"
    },
    {
        id: "fedplay",
        name: "📱 FED Play",
        category: "utility",
        featured: true,
        rating: 5.0, reviews: "1.2k",
        description: "The official FED Play app – install this to get all your favorite unofficial apps in one place.",
        downloadUrl: "https://www.mediafire.com/file/hnm5epejah3v63l/app-release%25233.apk/file",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: true,
        tags: ["apps", "utility", "fedplay"],
        imageUrl: "https://placehold.co/400x400/a5b4fc/0c0a1d?text=📱"
    },
    {
        id: "termux",
        name: "Termux",
        category: "utility",
        featured: false,
        rating: 4.7, reviews: "6.4k",
        description: "Terminal emulator for Android with a Linux package collection — dev on the go.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "missing"],
        imageUrl: "https://placehold.co/400x400/2d2d2d/ffffff?text=>_"
    },
    {
        id: "obsidian",
        name: "Obsidian",
        category: "utility",
        featured: true,
        rating: 4.8, reviews: "3.2k",
        description: "A second brain — local Markdown knowledge base with linked notes and graphs.",
        downloadUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "missing"],
        imageUrl: "https://cdn.simpleicons.org/obsidian/7C3AED"
    },
    {
        id: "vscode",
        name: "VS Code Server",
        category: "utility",
        featured: false,
        rating: 4.9, reviews: "5.5k",
        description: "Run Visual Studio Code in your browser — code anywhere from any device.",
        downloadUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "missing"],
        imageUrl: "https://placehold.co/400x400/007ACC/ffffff?text=VS"
    },

    // ===== PREMIUM-ONLY (extra) =====
    {
        id: "vip_arcade",
        name: "👑 VIP Arcade",
        category: "games",
        featured: false,
        rating: 4.8, reviews: "740",
        description: "Premium retro arcade collection — 500+ classic cabinets with no ads.",
        downloadUrl: "https://www.mediafire.com/file/premium/viparcade.apk/file",
        editorsChoice: true,
        isPremium: true, isPrivate: false, isAppStore: false,
        tags: ["apps", "games", "premium"],
        imageUrl: "https://placehold.co/400x400/fbbf24/0c0a1d?text=👑"
    },
    {
        id: "pro_studio",
        name: "🎨 Pro Studio",
        category: "creative",
        featured: false,
        rating: 4.9, reviews: "890",
        description: "Professional drawing & painting suite with 200+ brushes and layer support.",
        downloadUrl: "https://www.mediafire.com/file/premium/prostudio.apk/file",
        editorsChoice: true,
        isPremium: true, isPrivate: false, isAppStore: false,
        tags: ["apps", "creative", "premium"],
        imageUrl: "https://placehold.co/400x400/fbbf24/0c0a1d?text=🎨"
    },

    // ===== PRIVATE-ONLY (extra) =====
    {
        id: "vault_files",
        name: "🔒 Vault Files",
        category: "utility",
        featured: false,
        rating: 4.7, reviews: "150",
        description: "Encrypted file vault for sensitive documents. Invitation required.",
        downloadUrl: null,
        editorsChoice: false,
        isPremium: false, isPrivate: true, isAppStore: false,
        creatorContact: "https://t.me/vaultfiles",
        tags: ["apps", "utility", "private"],
        imageUrl: "https://placehold.co/400x400/60a5fa/0c0a1d?text=🔐"
    },

    // ===== FED ORIGINALS (extra) =====
    {
        id: "fed_wallet",
        name: "💎 FED Wallet",
        category: "utility",
        featured: true,
        rating: 4.8, reviews: "1.8k",
        description: "FED Play's native crypto wallet — self-custody, swap, and staking built in.",
        downloadUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false,
        tags: ["apps", "utility", "fed_originals"],
        imageUrl: "https://placehold.co/400x400/a5b4fc/0c0a1d?text=💎"
    },

    // ===== APP STORE INSTALLERS =====
    {
        id: "fed_store_ios",
        name: "📱 FED Play (iOS)",
        category: "utility",
        featured: true,
        rating: 4.9, reviews: "900",
        description: "Install FED Play on iPhone & iPad via the FED App Store — no jailbreak required.",
        downloadUrl: "https://www.mediafire.com/file/hnm5epejah3v63l/app-release%25233.apk/file",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: true,
        tags: ["apps", "utility", "appstore"],
        imageUrl: "https://placehold.co/400x400/a5b4fc/0c0a1d?text=📱"
    },
    {
        id: "fed_store_desktop",
        name: "💻 FED Play Desktop",
        category: "utility",
        featured: false,
        rating: 4.8, reviews: "1.1k",
        description: "FED Play for Windows, macOS & Linux — the full store on your desktop.",
        downloadUrl: "https://www.mediafire.com/file/hnm5epejah3v63l/app-release%25233.apk/file",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: true,
        tags: ["apps", "utility", "appstore"],
        imageUrl: "https://placehold.co/400x400/a5b4fc/0c0a1d?text=💻"
    },
    {
        id: "fed_store_tv",
        name: "📺 FED Play TV",
        category: "movies",
        featured: false,
        rating: 4.7, reviews: "640",
        description: "FED Play optimized for Android TV & Fire Stick — big-screen browsing & casting.",
        downloadUrl: "https://www.mediafire.com/file/hnm5epejah3v63l/app-release%25233.apk/file",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: true,
        tags: ["apps", "movies", "appstore"],
        imageUrl: "https://placehold.co/400x400/a5b4fc/0c0a1d?text=📺"
    },

    // ===== SURF FED EXTENSIONS (Streamlit web extensions) =====
    {
        id: "fed_gram",
        name: "FED-GRAM",
        category: "extensions",
        featured: true,
        rating: 4.9, reviews: "1.8k",
        description: "Universal social media downloader built with Streamlit. Paste any link from 18+ platforms (Instagram, TikTok, YouTube, Twitter, Reddit & more) and grab images, videos, reels & audio in one click.",
        downloadUrl: "https://github.com/FED-OS/FED-GRAM",
        streamlitUrl: "https://fed-gram-67erpbx6pmtkenc5hjczwc.streamlit.app/",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions", "fed_originals"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=FED-GRAM"
    },
    {
        id: "surf_fed_browser",
        name: "Surf Fed",
        category: "extensions",
        featured: true,
        rating: 4.8, reviews: "920",
        description: "The Streamlit-powered web browser at the heart of it all. Install extensions, browse the fed web, and run Python-native tools right in your sidebar.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions", "appstore"],
        imageUrl: "surf-fed-logo.png"
    },
    {
        id: "ext_media_grabber",
        name: "Media Grabber",
        category: "extensions",
        featured: false,
        rating: 4.6, reviews: "340",
        description: "One-click media extraction for any web page. Pulls images, videos, and audio into a clean Streamlit gallery with batch download.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=📷"
    },
    {
        id: "ext_ad_guard",
        name: "Ad Guard",
        category: "extensions",
        featured: false,
        rating: 4.7, reviews: "510",
        description: "Streamlit-based ad & tracker blocker for Surf Fed. Lightweight filter lists with per-site toggles and live block stats.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=🛡️"
    },
    {
        id: "ext_dark_reader",
        name: "Dark Reader",
        category: "extensions",
        featured: false,
        rating: 4.5, reviews: "280",
        description: "Auto dark-mode for every site in Surf Fed. Smart contrast adjustment with warm-light sliders, all in a Streamlit panel.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=🌙"
    },
    {
        id: "ext_ai_sidebar",
        name: "AI Sidebar",
        category: "extensions",
        featured: false,
        rating: 4.8, reviews: "670",
        description: "Chat with AI while you browse. Summarize pages, ask questions, and generate content from a Streamlit sidebar in Surf Fed.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: false,
        isPremium: true, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions", "premium"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=🤖"
    },
    {
        id: "ext_bookmarks",
        name: "Bookmark Vault",
        category: "extensions",
        featured: false,
        rating: 4.4, reviews: "190",
        description: "Tag, search, and sync your bookmarks across devices. Streamlit dashboard with full-text search and collections.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: false,
        isPremium: false, isPrivate: false, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=🔖"
    },
    {
        id: "ext_password_vault",
        name: "Password Vault",
        category: "extensions",
        featured: false,
        rating: 4.9, reviews: "430",
        description: "Encrypted password manager extension for Surf Fed. Auto-fill, generator, and security audit — all in a Streamlit UI.",
        downloadUrl: "",
        streamlitUrl: "",
        editorsChoice: true,
        isPremium: false, isPrivate: true, isAppStore: false, isExtension: true,
        tags: ["apps", "extensions", "private"],
        imageUrl: "https://placehold.co/400x400/0EA5E9/0c0a1d?text=🔐"
    }
];

// Tab metadata — drives sidebar, badges, page heroes
const TABS = [
    { id: "apps",          label: "Apps",            icon: "apps",                href: "index.html",         emoji: "📦" },
    { id: "games",         label: "Games",           icon: "sports_esports",      href: "games.html",         emoji: "🎮" },
    { id: "movies",        label: "Movies & TV",     icon: "local_movies",        href: "movies.html",        emoji: "🎬" },
    { id: "creative",      label: "Creative",        icon: "palette",             href: "creative.html",      emoji: "🎨" },
    { id: "utility",       label: "Utility",         icon: "build",               href: "utility.html",       emoji: "🛠️" },
    { id: "fed_originals", label: "FED Originals",   icon: "favorite",            href: "fed-originals.html", emoji: "❤️" },
    { id: "missing",       label: "Missing apps",    icon: "redeem",              href: "missing.html",       emoji: "🎁" },
    { id: "premium",       label: "Premium",         icon: "workspace_premium",   href: "premium.html",       emoji: "💎", cls: "premium" },
    { id: "private",       label: "Private",         icon: "lock",                href: "private.html",       emoji: "🔒", cls: "private" },
    { id: "appstore",      label: "App Store",       icon: "storefront",          href: "appstore.html",      emoji: "📱", cls: "appstore" },
    { id: "extensions",    label: "Surf Fed Ext.",   icon: "extension",           href: "extensions.html",    emoji: "🌊", cls: "extensions" }
];

// Category chips shown in the top category bar
const CHIPS = [
    { cat: "all",       label: "✨ All" },
    { cat: "featured",  label: "⭐ Featured" },
    { cat: "premium",   label: "💎 Premium", cls: "premium-chip" },
    { cat: "private",   label: "🔒 Private", cls: "private-chip" },
    { cat: "appstore",  label: "📱 App Store", cls: "appstore-chip" },
    { cat: "social",    label: "💬 Social" },
    { cat: "creative",  label: "🎨 Creative" },
    { cat: "utility",   label: "🛠️ Utility" },
    { cat: "games",     label: "🎮 Games" },
    { cat: "movies",    label: "🎬 Movies" },
    { cat: "extensions", label: "🌊 Surf Fed Ext.", cls: "extensions-chip" }
];

if (typeof window !== 'undefined') { window.APPS = APPS; window.TABS = TABS; window.CHIPS = CHIPS; }
